cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
    - language: java
      stage: Concert Demos
      jdk:
        - openjdk13
      cache:
        directories:
        - .autoconf
        - $HOME/.m2
      script:
        - mvn clean install package
        - cd concert-demos-rest-service-mvc
        - mvn coveralls:report -DrepoToken=${COVERALLS_TOKEN}
        - cd ..
        - cd concert-demos-rest-service-webflux
        - mvn coveralls:report -DrepoToken=${COVERALLS_TOKEN}
        - cd ..
        - cd concerts-demos-data
        - mvn coveralls:report -DrepoToken=${COVERALLS_TOKEN}
        - cd ..
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java Kotlin $(find **/jacoco.xml -printf -r %p)
