cache:
  directories:
  - .autoconf
  - $HOME/.m2
jobs:
  include:
    - language: java
      stage: Concert Demos
      jdk:
        - openjdk13
      cache:
        directories:
        - .autoconf
        - $HOME/.m2
      script:
        - mvn clean install package coveralls:report -DrepoToken=${COVERALLS_TOKEN}
        - bash <(curl -s https://codecov.io/bash)
        - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin $(find **/jacoco*.xml -printf '-r %p ')
