version: "3.7"
services:
  postgres:
    hostname: postgres
    build:
      context: ./docker-psql/.
    env_file:
      - ./docker-psql/.env
    volumes:
      - ./docker-psql/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=concertsdbmvc,concertsdbwebflux
    ports:
      - "5432:5432"
  concerts:
    hostname: concerts
    build:
      context: .
    ports:
      - "8085:80"
      - "8081:8081"
      - "8082:8082"
