version: "3.7"
services:
  postgres:
    hostname: postgres
    build:
      context: ./docker-psql/.
    env_file: ./docker-psql/.env
    user: postgres
    volumes:
      - ./docker-psql/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  mvc:
    hostname: mvc
    build:
      context: ./concert-demos-rest-service-mvc/.
    ports:
      - "8080:8080"

  webflux:
    hostname: webflux
    build:
      context: ./concert-demos-rest-service-webflux/.
    ports:
      - "8081:8081"

