version: "2"
services:
  concerts:
    hostname: concerts
    build:
      context: .
    ports:
      - "8085:80"
      - "8081:8081"
      - "8082:8082"
  postgres:
    hostname: postgres
    build:
      context: docker-psql/.
    env_file:
      - docker-psql/.env
