cypress-open:
	yarn && npm run cypress
cypress-electron:
	yarn && npm run cypress:run:electron
cypress-chrome:
	yarn && npm run cypress:run:chrome
cypress-firefox:
	yarn && npm run cypress:run:firefox
