name: concert-demos-root-PR

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      -  '**'
      - '!master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report
