name: concert-demos-root-e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 4
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 4
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 4
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-firefox

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start Docker
        uses: nick-fields/retry@v3
        with:
          max_attempts: 4
          retry_on: error
          timeout_seconds: 2400
          command: |
            make dcup-full-action

      - name: Docker Startup Fail!
        if: failure()
        run: |
          make docker-logs

      - name: Run Cypress
        run: make cypress-edge
