name: concert-demos-root-e2e

on:
  push:
    branches: [ master ]

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-firefox
